Bookish/Bookish/Models/Author.cs
namespace Bookish
{
    public class Author
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Book> Books { get; set; }
    }


}

Bookish/Bookish/Models/Book.cs
namespace Bookish
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public List<Author> Authors { get; set; }
        public Genre Genre { get; set; }
        public string CoverImageUrl { get; set; }
        public int YearPublished { get; set; }
        public string Blurb { get; set; }
        public List<Copy> Copies { get; set; }
    }
}

Bookish/Bookish/Models/Copy.cs
namespace Bookish
{
    public class Copy
    {
        public int Id { get; set; }
        public Book Book { get; set; }

    }
}

Bookish/Bookish/Models/CreateBook.cs
namespace Bookish.Models
{
    public class CreateBook
    {
        public string Title { get; set; }
        public string AuthorId { get; set; }
        public string CoverImageUrl { get; set; }
        public string YearPublished { get; set; }
        public string Blurb { get; set; }
        public int GenreId { get; set; }
    }
}

Bookish/Bookish/Models/ErrorViewModel.cs
namespace Bookish.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Bookish/Bookish/Models/Genre.cs
namespace Bookish
{
    public class Genre
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Book> Books { get; set; }
    }
}

Bookish/Bookish/Models/Member.cs
namespace Bookish
{
    public class Member
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
    }
}

Bookish/Bookish/Models/MemberCopy.cs
namespace Bookish
{
    public class MemberCopy
    {
        public int Id { get; set; }
        public Copy Copy { get; set; }
        public Member Member { get; set; }
        public DateTime DueDate { get; set; }
        public bool Returned { get; set; }
    }
}

Bookish/Bookish/Controllers/BookController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bookish.Models;
using Bookish.Models.Requests;

namespace Bookish.Controllers;
using Bookish.Services;

public class BookController : Controller
{
    private readonly ILogger<BookController> _logger;
    private BookService _bookService;

    public BookController(ILogger<BookController> logger)
    {
        _logger = logger;
        _bookService = new BookService();
    }

    public IActionResult Index()
    {
        List<Book> books = _bookService.GetAllBooks();
        return View(books);
    }

    [HttpPost("/Book")]
    public IActionResult CreateBook([FromBody] CreateBookRequest request)
    {
        Book book = _bookService.CreateBook(request);
        List<Book> books = new List<Book>();
        books.Add(book);
        return View("Index", books);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(
            new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }
        );
    }
}

Bookish/Bookish/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bookish.Models;

namespace Bookish.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Bookish/Bookish/Controllers/LibrarianController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bookish.Models;

namespace Bookish.Controllers;

public class LibrarianController : Controller
{
    private readonly ILogger<LibrarianController> _logger;

    public LibrarianController(ILogger<LibrarianController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Bookish/Bookish/Controllers/MemberController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bookish.Models;
using Bookish.Services;

namespace Bookish.Controllers;

public class MemberController : Controller
{
    private readonly ILogger<MemberController> _logger;
    private MemberService _memberService;
     

    public MemberController(ILogger<MemberController> logger)
    {
        _logger = logger;
        _memberService = new MemberService();
        
    }

    public IActionResult Index()
    {
        
        List<Member> members = _memberService.GetAllMembers();
        return View(members);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Bookish/Bookish/Views/Book/CreateBook.cshtml
@model CreateBook
@{
    ViewData["Title"] = "Create Book";
}

<div class="text-center">
    <h1 class="display-4">Create New Book</h1>
    <form asp-controller="Book" asp-action="CreateBook" method="post">
        Title: <input asp-for="Title" /><br />
        Author ID: <input asp-for="AuthorId" /><br />
        Cover image URL: <input asp-for="CoverImageUrl" /><br />
        Blurb: <input asp-for="Blurb" /><br />
        Genre name: <input asp-for="GenreId" /><br />
        Year: <input asp-for="YearPublished" />
        <button type="submit">Create book</button>
    </form>
</div>

Bookish/Bookish/Views/Book/Index.cshtml
@model List<Book>
@{
    ViewData["Title"] = "Books";
}

<div class="text-center">
    @foreach(Book book in Model)
    {
        <p>@book.Title, @book.Genre.Name, @book.YearPublished</p>
        @foreach(Author author in book.Authors)
        {
            <p>@author.Name</p>
        }
        <img width="250px" src="@book.CoverImageUrl"></img>
    }
    
</div>

Bookish/Bookish/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Bookish/Bookish/Views/Librarian/Index.cshtml
@{
    ViewData["Title"] = "Librarian's Page";
}

<div class="text-center">
    <h1 class="display-4">Librarian's Page</h1>
</div>

Bookish/Bookish/Views/Member/Index.cshtml
@model List<Member>
@{
    ViewData["Title"] = "Members";
}

<div class="text-center">
    @foreach(Member member in Model)
    {
        <p>@member.Name</p>
        <p>@member.Address</p>
        <p>@member.Email</p>
    }
    
</div>

Bookish/Bookish/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookish</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bookish.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookish</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="">Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="">Member</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Librarian" asp-action="">Librarian</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bookish - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>